menu:
  Home: /
  Archives: /archives

widgets: 
- search
- category
- tag

excerpt_link: Read More

twitter:
  username:
  show_replies: false
  tweet_count: 5

addthis:
  enable:
  pubid:
  facebook:
  twitter:
  google:
  pinterest:

fancybox: false

google_analytics:
rss: